import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "calc(env(safe-area-inset-top, 0px) + 20px) 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#F7F7F8",
        animation: "fadeIn 0.4s ease-out",
    },
    header: {
        fontWeight: 700,
        fontSize: 22,
        marginBottom: 18,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInDown 0.5s ease-out",
    },
    monthTitle: {
        fontWeight: 700,
        fontSize: 14,
        color: "#7B3F98",
        marginTop: 20,
        marginBottom: 10,
        fontFamily: "Rubik, sans-serif",
        letterSpacing: 0.3,
        animation: "fadeInUp 0.4s ease-out both",
    },
    typeChip: {
        fontSize: 11,
        height: 24,
        borderRadius: 999,
        backgroundColor: "#F3EAF7",
        color: "#7B3F98",
        transition: "transform 0.2s ease",
        "&:hover": { transform: "scale(1.05)" },
    },
    rsvpRow: {
        display: "flex",
        flexDirection: "column",
        gap: 14,
        marginTop: 22,
        paddingTop: 18,
        borderTop: "1px solid #F1F2F4",
    },
    rsvpTitle: {
        color: "#1F1F1F",
        fontWeight: 800,
        fontSize: 16,
        fontFamily: "Rubik, sans-serif",
    },
    rsvpStatus: {
        marginTop: 4,
        color: "#6B7280",
        fontWeight: 700,
        fontSize: 13,
        fontFamily: "Rubik, sans-serif",
    },
    rsvpGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 10,
    },
    rsvpOptionCard: {
        minHeight: 94,
        borderRadius: "18px !important",
        padding: "14px 10px !important",
        display: "flex",
        flexDirection: "column" as const,
        gap: "8px !important",
        fontFamily: "Rubik, sans-serif !important",
        textTransform: "none !important" as const,
        transition: "transform 0.18s ease, box-shadow 0.18s ease, background-color 0.18s ease",
        "&:active": { transform: "scale(0.98)" },
    },
    rsvpOptionIcon: {
        fontSize: 24,
        lineHeight: 1,
        fontFamily: "Rubik, sans-serif",
    },
    rsvpOptionLabel: {
        fontSize: 13,
        fontWeight: 800,
        lineHeight: 1.25,
        fontFamily: "Rubik, sans-serif",
        textAlign: "center" as const,
    },
    empty: {
        textAlign: "center" as const,
        color: "#6B7280",
        marginTop: 60,
        fontSize: 15,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeIn 0.6s ease-out",
    },
    backButton: {
        color: "#7B3F98",
        fontWeight: 700,
        fontFamily: "Rubik, sans-serif",
        marginBottom: 8,
        textTransform: "none" as const,
    },
    detailsHeader: {
        display: "grid",
        gridTemplateColumns: "44px 1fr 44px",
        alignItems: "center",
        marginBottom: 14,
    },
    detailsBackButton: {
        width: 40,
        height: 40,
        color: "#7B3F98",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        "&:hover": {
            backgroundColor: "#F3EAF7",
        },
    },
    detailsHeaderTitle: {
        justifySelf: "center",
        color: "#1F1F1F",
        fontWeight: 800,
        fontSize: 18,
        fontFamily: "Rubik, sans-serif",
    },
    detailsCard: {
        borderRadius: 20,
        padding: 24,
        backgroundColor: "#fff",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
    },
    detailsTitle: {
        fontWeight: 800,
        fontSize: 24,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        marginTop: 14,
        marginBottom: 16,
        lineHeight: 1.25,
    },
    detailsMetaGroup: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    detailsMetaRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    detailsMetaIcon: {
        width: 32,
        height: 32,
        borderRadius: "50%",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#7B3F98",
        backgroundColor: "#F3EAF7",
        flexShrink: 0,
    },
    detailsMeta: {
        fontSize: 14,
        color: "#6B7280",
        fontWeight: 700,
        fontFamily: "Rubik, sans-serif",
    },
    description: {
        fontSize: 14,
        color: "#1F1F1F",
        lineHeight: 1.7,
        marginTop: 18,
        padding: 14,
        borderRadius: 16,
        backgroundColor: "#FAFAFB",
        fontFamily: "Rubik, sans-serif",
    },
});
