import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding:
            "calc(env(safe-area-inset-top, 0px) + 18px) 16px calc(var(--shell-bottom-inset, 0px) + 20px)",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100dvh",
        backgroundColor: "var(--color-canvas, #f5f6f8)",
        animation: "fadeIn 180ms var(--ease-out, ease-out)",
    },
    header: {
        fontWeight: 800,
        fontSize: 24,
        marginBottom: 18,
        color: "var(--color-text, #1d1d1f)",
        lineHeight: 1.15,
        letterSpacing: "-0.01em",
    },
    monthTitle: {
        fontWeight: 800,
        fontSize: 14,
        color: "var(--color-text-secondary, #51565c)",
        marginTop: 20,
        marginBottom: 10,
        letterSpacing: 0,
        animation: "fadeInUp 180ms var(--ease-out, ease-out) both",
    },
    typeChip: {
        fontSize: 11,
        height: 26,
        borderRadius: "var(--radius-sm, 10px)",
        backgroundColor: "var(--color-brand-soft)",
        color: "var(--color-brand)",
        border: "1px solid rgba(var(--color-brand-rgb), 0.18)",
    },
    rsvpRow: {
        display: "flex",
        flexDirection: "column",
        gap: 14,
        marginTop: 22,
        paddingTop: 18,
        borderTop: "1px solid var(--color-border-subtle, #e9ebef)",
    },
    rsvpHeader: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 12,
    },
    rsvpTitle: {
        color: "var(--color-text, #1d1d1f)",
        fontWeight: 800,
        fontSize: 16,
    },
    rsvpStatus: {
        marginTop: 4,
        color: "var(--color-text-muted, #6e737a)",
        fontWeight: 700,
        fontSize: 13,
    },
    rsvpGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 10,
    },
    saveCalendarIconButton: {
        flexShrink: 0,
        width: "44px !important",
        height: "44px !important",
        color: "var(--color-brand) !important",
        backgroundColor: "rgba(255, 255, 255, 0.94) !important",
        boxShadow: "0 6px 16px rgba(45, 35, 43, 0.16) !important",
        border: "1px solid rgba(228, 215, 235, 0.9) !important",
        "&:hover": {
            color: "#fff !important",
            backgroundColor: "var(--color-brand) !important",
        },
    },
    rsvpOptionCard: {
        minHeight: 96,
        borderRadius: "var(--radius-lg, 18px) !important",
        padding: "14px 10px !important",
        display: "flex",
        flexDirection: "column" as const,
        gap: "8px !important",
        textTransform: "none !important" as const,
        transition:
            "transform var(--transition-fast, 140ms ease), box-shadow var(--transition-fast, 140ms ease), background-color var(--transition-fast, 140ms ease), border-color var(--transition-fast, 140ms ease)",
        "&:active": { transform: "scale(0.98)" },
    },
    rsvpOptionIcon: {
        fontSize: 24,
        lineHeight: 1,
    },
    rsvpOptionLabel: {
        fontSize: 13,
        fontWeight: 800,
        lineHeight: 1.25,
        textAlign: "center" as const,
    },
    empty: {
        textAlign: "center" as const,
        color: "var(--color-text-muted, #6e737a)",
        marginTop: 60,
        fontSize: 15,
        animation: "fadeIn 180ms var(--ease-out, ease-out)",
    },
    backButton: {
        color: "var(--color-brand)",
        fontWeight: 700,
        marginBottom: 8,
        textTransform: "none" as const,
    },
    detailsHeader: {
        display: "grid",
        gridTemplateColumns: "44px 1fr 44px",
        alignItems: "center",
        marginBottom: 14,
    },
    detailsBackButton: {
        width: 44,
        height: 44,
        color: "var(--color-brand)",
        backgroundColor: "var(--color-surface-elevated, rgba(255,255,255,0.82))",
        boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16,24,40,0.07))",
        backdropFilter: "blur(16px) saturate(160%)",
        "&:hover": {
            backgroundColor: "var(--color-brand-soft)",
        },
    },
    detailsImageButton: {
        justifySelf: "end",
        width: 44,
        height: 44,
        color: "var(--color-brand)",
        backgroundColor: "var(--color-surface-elevated, rgba(255,255,255,0.82))",
        boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16,24,40,0.07))",
        backdropFilter: "blur(16px) saturate(160%)",
        "&:hover": {
            backgroundColor: "var(--color-brand-soft)",
        },
    },
    detailsHeaderTitle: {
        justifySelf: "center",
        color: "var(--color-text, #1d1d1f)",
        fontWeight: 800,
        fontSize: 18,
    },
    detailsCard: {
        position: "relative" as const,
        borderRadius: "var(--radius-xl, 22px)",
        padding: 24,
        backgroundColor: "var(--color-surface, #fff)",
        border: "1px solid var(--color-border-subtle, #e9ebef)",
        boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16,24,40,0.07))",
        overflow: "hidden",
    },
    detailsCardWithImage: {
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundColor: "#241f25",
        borderColor: "rgba(255, 255, 255, 0.2)",
        boxShadow: "0 18px 36px rgba(28, 35, 38, 0.22)",
        "&::before": {
            content: '""',
            position: "absolute" as const,
            inset: 0,
            background:
                "linear-gradient(180deg, rgba(12, 15, 18, 0.32) 0%, rgba(12, 15, 18, 0.38) 42%, rgba(12, 15, 18, 0.56) 100%)",
            pointerEvents: "none" as const,
            zIndex: 0,
        },
        "& > *": {
            position: "relative" as const,
            zIndex: 1,
        },
        "& $typeChip": {
            backgroundColor: "rgba(255, 255, 255, 0.88)",
            color: "var(--color-brand)",
        },
        "& $saveCalendarIconButton": {
            color: "#fff !important",
            backgroundColor: "rgba(0, 0, 0, 0.30) !important",
            borderColor: "rgba(255, 255, 255, 0.34) !important",
            backdropFilter: "blur(8px)",
            boxShadow: "0 8px 18px rgba(0, 0, 0, 0.22) !important",
            "&:hover": {
                backgroundColor: "rgba(123, 63, 152, 0.92) !important",
                borderColor: "rgba(255, 255, 255, 0.68) !important",
            },
        },
        "& $detailsTitle, & $description, & $rsvpTitle, & $rsvpStatus": {
            color: "#fff",
            textShadow: "0 1px 4px rgba(0, 0, 0, 0.48)",
        },
        "& $detailsMeta": {
            color: "rgba(255, 255, 255, 0.92)",
            textShadow: "0 1px 3px rgba(0, 0, 0, 0.42)",
        },
        "& $detailsMetaIcon": {
            color: "#fff",
            backgroundColor: "rgba(255, 255, 255, 0.22)",
            backdropFilter: "blur(8px)",
        },
        "& $description": {
            backgroundColor: "rgba(0, 0, 0, 0.24)",
            backdropFilter: "blur(8px)",
        },
        "& $rsvpRow": {
            borderTopColor: "rgba(255, 255, 255, 0.24)",
        },
    },
    detailsTitle: {
        fontWeight: 800,
        fontSize: 24,
        color: "var(--color-text, #1d1d1f)",
        marginTop: 14,
        marginBottom: 16,
        lineHeight: 1.25,
        letterSpacing: "-0.01em",
        overflowWrap: "anywhere" as const,
    },
    detailsMetaGroup: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    detailsMetaRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    detailsMetaIcon: {
        width: 32,
        height: 32,
        borderRadius: "50%",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        color: "var(--color-brand)",
        backgroundColor: "var(--color-brand-soft)",
        flexShrink: 0,
    },
    detailsMeta: {
        fontSize: 14,
        color: "var(--color-text-secondary, #51565c)",
        fontWeight: 700,
        overflowWrap: "anywhere" as const,
    },
    description: {
        fontSize: 14,
        color: "var(--color-text, #1d1d1f)",
        lineHeight: 1.7,
        marginTop: 18,
        padding: 14,
        borderRadius: "var(--radius-md, 14px)",
        backgroundColor: "var(--color-canvas-warm, #faf9fb)",
        overflowWrap: "anywhere" as const,
    },
    imageViewerPaper: {
        direction: "rtl",
        display: "flex",
        flexDirection: "column" as const,
        minWidth: 0,
        height: "100dvh",
        maxHeight: "100dvh",
        backgroundColor: "#171419 !important",
        color: "#FFFFFF !important",
        overflow: "hidden",
    },
    imageViewerHeader: {
        minHeight: 64,
        padding: "calc(env(safe-area-inset-top, 0px) + 8px) 12px 8px",
        display: "grid",
        gridTemplateColumns: "44px minmax(0, 1fr) 44px",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(23, 24, 28, 0.94)",
        backdropFilter: "blur(18px) saturate(160%)",
        borderBottom: "1px solid rgba(255, 255, 255, 0.12)",
        flexShrink: 0,
    },
    imageViewerTitle: {
        gridColumn: 2,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap" as const,
        textAlign: "center" as const,
        fontSize: 16,
        fontWeight: 700,
    },
    imageViewerCloseButton: {
        gridColumn: 3,
        width: 44,
        height: 44,
        color: "#FFFFFF !important",
        backgroundColor: "rgba(255, 255, 255, 0.10) !important",
        "&:hover": {
            backgroundColor: "rgba(255, 255, 255, 0.18) !important",
        },
    },
    imageViewerContent: {
        flex: "1 1 auto",
        minHeight: 0,
        minWidth: 0,
        padding: 12,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        overflow: "auto",
        overscrollBehavior: "contain",
    },
    imageViewerImage: {
        display: "block",
        width: "auto",
        height: "auto",
        maxWidth: "100%",
        maxHeight: "100%",
        objectFit: "contain" as const,
    },
    imageViewerError: {
        minHeight: 180,
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        justifyContent: "center",
        gap: 12,
        color: "rgba(255, 255, 255, 0.82)",
        textAlign: "center" as const,
        fontFamily: "inherit",
    },
    imageViewerErrorIcon: {
        fontSize: "48px !important",
        color: "rgba(255, 255, 255, 0.58)",
    },
    imageViewerActions: {
        flexShrink: 0,
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "stretch",
        gap: 8,
        padding: "12px 16px calc(env(safe-area-inset-bottom, 0px) + 16px)",
        backgroundColor: "rgba(23, 24, 28, 0.94)",
        backdropFilter: "blur(18px) saturate(160%)",
        borderTop: "1px solid rgba(255, 255, 255, 0.12)",
    },
    imageDownloadButton: {
        minHeight: "48px !important",
        borderRadius: "12px !important",
        backgroundColor: "var(--color-primary) !important",
        fontWeight: "700 !important",
        textTransform: "none !important" as const,
        "&:hover": {
            backgroundColor: "var(--color-primary-dark) !important",
        },
    },
    imageDownloadHint: {
        color: "rgba(255, 255, 255, 0.76)",
        fontSize: "12px !important",
        textAlign: "center" as const,
    },
    "@media (max-width: 390px)": {
        root: {
            paddingInline: 12,
        },
        detailsCard: {
            padding: 18,
        },
        rsvpGrid: {
            gap: 8,
        },
        rsvpOptionLabel: {
            fontSize: 12,
        },
    },
    "@media (prefers-reduced-transparency: reduce)": {
        detailsBackButton: {
            backgroundColor: "var(--color-surface, #fff)",
            backdropFilter: "none",
        },
        detailsImageButton: {
            backgroundColor: "var(--color-surface, #fff)",
            backdropFilter: "none",
        },
        imageViewerHeader: {
            backdropFilter: "none",
        },
        imageViewerActions: {
            backdropFilter: "none",
        },
    },
});
