import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
  dialogPaper: {
    width: 1120,
    maxWidth: "96vw",
    borderRadius: 22,
    overflow: "hidden",
    fontFamily: "Rubik, sans-serif",
    animation: "scaleIn 0.35s cubic-bezier(0.4,0,0.2,1)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
  },
  header: {
    position: "relative" as const,
    background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
    color: "#fff",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: 700,
    fontSize: 18,
    fontFamily: "Rubik, sans-serif",
  },
  closeButton: {
    position: "absolute" as const,
    left: 8,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
      transform: "translateY(-50%) rotate(90deg)",
    },
  },
  addButton: {
    position: "absolute" as const,
    right: 8,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
    },
  },
  sendAssignmentsButtonWrap: {
    position: "absolute" as const,
    right: 52,
    top: "50%",
    transform: "translateY(-50%)",
    display: "inline-flex",
  },
  sendAssignmentsButton: {
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
    },
    "&.Mui-disabled": {
      color: "rgba(255,255,255,0.45)",
      backgroundColor: "rgba(255,255,255,0.08)",
    },
  },
  printSheetButtonWrap: {
    position: "absolute" as const,
    right: 96,
    top: "50%",
    transform: "translateY(-50%)",
    display: "inline-flex",
  },
  printSheetIconButton: {
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
    },
    "&.Mui-disabled": {
      color: "rgba(255,255,255,0.45)",
      backgroundColor: "rgba(255,255,255,0.08)",
    },
  },
  dialogContent: {
    direction: "rtl" as const,
    maxHeight: "min(72vh, 680px)",
    padding: "18px 20px",
    overflow: "hidden",
    backgroundColor: "#faf8f9",
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(154,81,136,0.2)",
      borderRadius: 3,
    },
  },
  dialogToolbar: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 14,
  },
  printSheetButton: {
    direction: "rtl" as const,
    color: "#7a3e6b",
    borderColor: "#e4d3df",
    backgroundColor: "#fff",
    border: "1px solid #e4d3df",
    borderRadius: 12,
    padding: "7px 14px",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 13,
    textTransform: "none" as const,
    boxShadow: "0 3px 10px rgba(45, 35, 43, 0.05)",
    "& .MuiButton-startIcon": {
      marginLeft: 8,
      marginRight: 0,
    },
    "&:hover": {
      backgroundColor: "#fbf7fa",
      borderColor: "#d8b8cf",
    },
    "&.Mui-disabled": {
      color: "#b8aeb5",
      borderColor: "#eee7ec",
      backgroundColor: "#fafafa",
    },
  },
  participantsGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr)",
    gap: 16,
    direction: "ltr" as const,
    minHeight: 0,
    height: "min(62vh, 560px)",
  },
  sectionColumn: {
    direction: "rtl" as const,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
    borderRadius: 16,
    boxShadow: "0 4px 16px rgba(45, 35, 43, 0.045)",
    overflow: "hidden",
  },
  sectionBody: {
    minHeight: 0,
    flex: 1,
    overflowY: "auto" as const,
    padding: "12px",
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(154,81,136,0.18)",
      borderRadius: 3,
    },
  },
  listItem: {
    padding: "10px 14px",
    borderRadius: 14,
    marginBottom: 8,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
    transition: "all 0.25s cubic-bezier(0.4,0,0.2,1)",
    animation: "fadeInUp 0.3s ease-out both",
    display: "flex",
    alignItems: "center",
    gap: 12,
    "&:hover": {
      backgroundColor: "#f8f4f9",
      transform: "translateX(4px)",
      boxShadow: "0 3px 12px rgba(154,81,136,0.1)",
    },
    "&:last-child": {
      marginBottom: 0,
    },
  },
  pairRow: {
    padding: "8px",
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "#fff",
    border: "1px solid #eadce7",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 12,
  },
  pairContent: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  pairPerson: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minWidth: 0,
    padding: "6px 8px",
    borderRadius: 10,
    backgroundColor: "#fbf7fa",
  },
  pairDivider: {
    color: "#9a5188",
    fontWeight: 700,
    fontSize: 16,
    fontFamily: "Rubik, sans-serif",
  },
  selectableItem: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 10,
    marginBottom: 0,
    backgroundColor: "transparent",
    border: "1px solid transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    color: "#333",
    textTransform: "none" as const,
    transition: "all 0.2s ease",
    minWidth: 0,
    "&:hover": {
      backgroundColor: "#f8f4f9",
      borderColor: "#d8b8cf",
    },
  },
  selectedItem: {
    backgroundColor: "#f3e8f0 !important",
    borderColor: "#9a5188 !important",
    boxShadow: "0 0 0 2px rgba(154,81,136,0.12)",
  },
  attendeeRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
  },
  participantActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    paddingInlineStart: 4,
  },
  sectionTitle: {
    margin: 0,
    padding: "12px 14px",
    color: "#5d4c57",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 14,
    backgroundColor: "#fbf7fa",
    borderBottom: "1px solid #f0ecef",
  },
  sectionEmpty: {
    margin: "4px 2px 8px",
    color: "#aaa",
    fontFamily: "Rubik, sans-serif",
    fontSize: 12,
  },
  personName: {
    maxWidth: "100%",
    color: "#333",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  personMeta: {
    maxWidth: "100%",
    color: "#888",
    fontFamily: "Rubik, sans-serif",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  loadingState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 200,
  },
  attendeeName: {
    textAlign: "right" as const,
    fontFamily: "Rubik, sans-serif",
    "& .MuiListItemText-primary": {
      fontWeight: 600,
      fontSize: 14,
      color: "#333",
    },
    "& .MuiListItemText-secondary": {
      fontSize: 12,
      color: "#999",
    },
  },
  avatar: {
    width: 38,
    height: 38,
    backgroundColor: "#f3e8f0",
    color: "#9a5188",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "Rubik, sans-serif",
    transition: "transform 0.3s ease",
  },
  deleteButton: {
    width: 34,
    height: 34,
    flexShrink: 0,
    color: "#b85c5c",
    backgroundColor: "#fff7f7",
    border: "1px solid #f1d4d4",
    transition: "all 0.25s ease",
    "&:hover": {
      color: "#e53935",
      backgroundColor: "#fff0f0",
      borderColor: "#e8bebe",
    },
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#bbb",
    fontFamily: "Rubik, sans-serif",
  },
  countBadge: {
    fontFamily: "Rubik, sans-serif",
    fontSize: 12,
    fontWeight: 600,
    color: "rgba(255,255,255,0.8)",
    marginTop: 2,
  },
  printPreviewDialogPaper: {
    width: 860,
    maxWidth: "94vw",
    borderRadius: 18,
    overflow: "hidden",
    fontFamily: "Rubik, sans-serif",
    direction: "rtl" as const,
    backgroundColor: "#f6f4f5",
  },
  printPreviewHeader: {
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "14px 20px",
    color: "#fff",
    background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
  },
  printPreviewTitle: {
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 17,
  },
  printPreviewCloseButton: {
    position: "absolute" as const,
    left: 10,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.28)",
    },
  },
  printDialogContent: {
    maxHeight: "min(74vh, 760px)",
    overflowY: "auto" as const,
    padding: "20px",
    backgroundColor: "#f6f4f5",
  },
  printPreviewActions: {
    direction: "rtl" as const,
    padding: "12px 18px 16px",
    gap: 10,
    backgroundColor: "#fff",
    borderTop: "1px solid #eee7ec",
    "& .MuiButton-startIcon": {
      marginLeft: 8,
      marginRight: 0,
    },
  },
  printPrimaryButton: {
    backgroundColor: "#7a3e6b",
    color: "#fff",
    borderRadius: 10,
    padding: "7px 14px",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    textTransform: "none" as const,
    "&:hover": {
      backgroundColor: "#69335c",
    },
  },
  printSecondaryButton: {
    color: "#6d5a66",
    borderRadius: 10,
    padding: "7px 14px",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    textTransform: "none" as const,
    "&:hover": {
      backgroundColor: "#f7f1f5",
    },
  },
  shabbatSheet: {
    direction: "rtl" as const,
    color: "#111",
    backgroundColor: "#fff",
    width: "100%",
    maxWidth: 780,
    margin: "0 auto",
    padding: "28px 34px",
    borderRadius: 8,
    border: "1px solid #e6e0e4",
    boxShadow: "0 8px 28px rgba(20, 15, 18, 0.08)",
    fontFamily: "Rubik, Arial, sans-serif",
  },
  printTitleBlock: {
    textAlign: "center" as const,
    marginBottom: 22,
    paddingBottom: 14,
    borderBottom: "2px solid #111",
  },
  printOrgTitle: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 18,
    fontWeight: 700,
    color: "#111",
    marginBottom: 4,
  },
  printDocumentTitle: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 30,
    fontWeight: 800,
    color: "#111",
  },
  printEventInfoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "10px 18px",
    marginBottom: 24,
    padding: 14,
    border: "1px solid #d8d3d6",
    borderRadius: 6,
    backgroundColor: "#fafafa",
  },
  printEventInfoItem: {
    display: "grid",
    gridTemplateColumns: "86px minmax(0, 1fr)",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  printInfoLabel: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 12,
    fontWeight: 700,
    color: "#555",
  },
  printInfoValue: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: "#111",
    overflowWrap: "anywhere" as const,
  },
  printSection: {
    marginTop: 18,
    breakInside: "avoid" as const,
    pageBreakInside: "avoid" as const,
  },
  printSectionTitle: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 17,
    fontWeight: 800,
    color: "#111",
    marginBottom: 8,
    paddingBottom: 6,
    borderBottom: "1px solid #222",
  },
  printTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    tableLayout: "fixed" as const,
    "& .MuiTableCell-root": {
      border: "1px solid #222",
      padding: "7px 10px",
      fontFamily: "Rubik, Arial, sans-serif",
      fontSize: 13,
      color: "#111",
      textAlign: "right" as const,
      backgroundColor: "#fff",
    },
    "& .MuiTableHead-root .MuiTableCell-root": {
      fontWeight: 800,
      backgroundColor: "#f0f0f0",
    },
    "& .MuiTableRow-root": {
      breakInside: "avoid" as const,
      pageBreakInside: "avoid" as const,
    },
  },
  printEmptyText: {
    fontFamily: "Rubik, Arial, sans-serif",
    fontSize: 13,
    color: "#555",
    border: "1px solid #d8d3d6",
    borderRadius: 6,
    padding: "10px 12px",
    backgroundColor: "#fafafa",
  },
  "@media print": {
    "@page": {
      size: "A4 portrait",
      margin: "14mm",
    },
    "@global": {
      "html, body": {
        width: "210mm",
        minHeight: "297mm",
        background: "#fff !important",
      },
      "body *": {
        visibility: "hidden !important",
      },
      ".shabbat-print-root, .shabbat-print-root *": {
        visibility: "visible !important",
      },
      ".shabbat-print-root": {
        position: "absolute !important",
        inset: "0 auto auto 0 !important",
        width: "100% !important",
        maxWidth: "none !important",
        margin: "0 !important",
        padding: "0 !important",
        border: "0 !important",
        boxShadow: "none !important",
        borderRadius: "0 !important",
      },
      ".MuiBackdrop-root, .MuiDialogActions-root": {
        display: "none !important",
      },
    },
    printPreviewDialogPaper: {
      boxShadow: "none !important",
      backgroundColor: "#fff !important",
      width: "100% !important",
      maxWidth: "none !important",
      margin: "0 !important",
    },
    printPreviewHeader: {
      display: "none !important",
    },
    printDialogContent: {
      padding: "0 !important",
      margin: "0 !important",
      overflow: "visible !important",
      maxHeight: "none !important",
      backgroundColor: "#fff !important",
    },
    printPreviewActions: {
      display: "none !important",
    },
    printEventInfoGrid: {
      backgroundColor: "#fff !important",
    },
    printEmptyText: {
      backgroundColor: "#fff !important",
    },
    printSection: {
      breakInside: "avoid-page" as const,
      pageBreakInside: "avoid" as const,
    },
  },
  "@media (max-width: 960px)": {
    dialogPaper: {
      width: "calc(100vw - 24px)",
      maxWidth: "calc(100vw - 24px)",
    },
    dialogContent: {
      maxHeight: "72vh",
      overflowY: "auto" as const,
      padding: "14px",
    },
    participantsGrid: {
      gridTemplateColumns: "1fr",
      height: "auto",
      direction: "rtl" as const,
    },
    sectionBody: {
      maxHeight: 320,
    },
    printPreviewDialogPaper: {
      width: "calc(100vw - 20px)",
      maxWidth: "calc(100vw - 20px)",
    },
    printDialogContent: {
      padding: "12px",
    },
    shabbatSheet: {
      padding: "22px 18px",
    },
    printEventInfoGrid: {
      gridTemplateColumns: "1fr",
    },
  },
});
