import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
  dialogPaper: {
    width: 420,
    maxWidth: "90vw",
    borderRadius: 22,
    overflow: "hidden",
    fontFamily: "Rubik, sans-serif",
    animation: "scaleIn 0.35s cubic-bezier(0.4,0,0.2,1)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
  },
  header: {
    position: "relative" as const,
    background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
    color: "#fff",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: 700,
    fontSize: 18,
    fontFamily: "Rubik, sans-serif",
  },
  closeButton: {
    position: "absolute" as const,
    left: 8,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
      transform: "translateY(-50%) rotate(90deg)",
    },
  },
  dialogContent: {
    direction: "rtl" as const,
    maxHeight: 400,
    padding: "16px 20px",
    overflowY: "auto" as const,
    backgroundColor: "#faf8f9",
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(154,81,136,0.2)",
      borderRadius: 3,
    },
  },
  listItem: {
    padding: "10px 14px",
    borderRadius: 14,
    marginBottom: 8,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
    transition: "all 0.25s cubic-bezier(0.4,0,0.2,1)",
    animation: "fadeInUp 0.3s ease-out both",
    display: "flex",
    alignItems: "center",
    gap: 12,
    "&:hover": {
      backgroundColor: "#f8f4f9",
      transform: "translateX(4px)",
      boxShadow: "0 3px 12px rgba(154,81,136,0.1)",
    },
    "&:last-child": {
      marginBottom: 0,
    },
  },
  attendeeName: {
    textAlign: "right" as const,
    fontFamily: "Rubik, sans-serif",
    "& .MuiListItemText-primary": {
      fontWeight: 600,
      fontSize: 14,
      color: "#333",
    },
    "& .MuiListItemText-secondary": {
      fontSize: 12,
      color: "#999",
    },
  },
  avatar: {
    width: 38,
    height: 38,
    backgroundColor: "#f3e8f0",
    color: "#9a5188",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "Rubik, sans-serif",
    transition: "transform 0.3s ease",
  },
  deleteButton: {
    color: "#ccc",
    transition: "all 0.25s ease",
    "&:hover": {
      color: "#e53935",
      backgroundColor: "rgba(229,57,53,0.08)",
    },
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#bbb",
    fontFamily: "Rubik, sans-serif",
  },
  countBadge: {
    fontFamily: "Rubik, sans-serif",
    fontSize: 12,
    fontWeight: 600,
    color: "rgba(255,255,255,0.8)",
    marginTop: 2,
  },
});
