import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
  dialogPaper: {
    width: 460,
    maxWidth: "94vw",
    borderRadius: 22,
    overflow: "hidden",
    fontFamily: "Rubik, sans-serif",
    animation: "scaleIn 0.35s cubic-bezier(0.4,0,0.2,1)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
  },
  header: {
    position: "relative" as const,
    background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
    color: "#fff",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: 700,
    fontSize: 18,
    fontFamily: "Rubik, sans-serif",
  },
  closeButton: {
    position: "absolute" as const,
    left: 8,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
      transform: "translateY(-50%) rotate(90deg)",
    },
  },
  addButton: {
    position: "absolute" as const,
    right: 8,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.15)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.3)",
    },
  },
  dialogContent: {
    direction: "rtl" as const,
    maxHeight: 400,
    padding: "16px 20px",
    overflowY: "auto" as const,
    backgroundColor: "#faf8f9",
    "&::-webkit-scrollbar": {
      width: 6,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(154,81,136,0.2)",
      borderRadius: 3,
    },
  },
  listItem: {
    padding: "10px 14px",
    borderRadius: 14,
    marginBottom: 8,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
    transition: "all 0.25s cubic-bezier(0.4,0,0.2,1)",
    animation: "fadeInUp 0.3s ease-out both",
    display: "flex",
    alignItems: "center",
    gap: 12,
    "&:hover": {
      backgroundColor: "#f8f4f9",
      transform: "translateX(4px)",
      boxShadow: "0 3px 12px rgba(154,81,136,0.1)",
    },
    "&:last-child": {
      marginBottom: 0,
    },
  },
  pairRow: {
    padding: "8px",
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "#fff",
    border: "1px solid #eadce7",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 12,
  },
  pairContent: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  pairPerson: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minWidth: 0,
    padding: "6px 8px",
    borderRadius: 10,
    backgroundColor: "#fbf7fa",
  },
  pairDivider: {
    color: "#9a5188",
    fontWeight: 700,
    fontSize: 16,
    fontFamily: "Rubik, sans-serif",
  },
  selectableItem: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 10,
    marginBottom: 0,
    backgroundColor: "transparent",
    border: "1px solid transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    color: "#333",
    textTransform: "none" as const,
    transition: "all 0.2s ease",
    minWidth: 0,
    "&:hover": {
      backgroundColor: "#f8f4f9",
      borderColor: "#d8b8cf",
    },
  },
  selectedItem: {
    backgroundColor: "#f3e8f0 !important",
    borderColor: "#9a5188 !important",
    boxShadow: "0 0 0 2px rgba(154,81,136,0.12)",
  },
  attendeeRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
  },
  participantActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    paddingInlineStart: 4,
  },
  sectionTitle: {
    margin: "14px 0 8px",
    color: "#5d4c57",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 14,
  },
  sectionEmpty: {
    marginBottom: 8,
    color: "#aaa",
    fontFamily: "Rubik, sans-serif",
    fontSize: 12,
  },
  personName: {
    maxWidth: "100%",
    color: "#333",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  personMeta: {
    maxWidth: "100%",
    color: "#888",
    fontFamily: "Rubik, sans-serif",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  loadingState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 200,
  },
  attendeeName: {
    textAlign: "right" as const,
    fontFamily: "Rubik, sans-serif",
    "& .MuiListItemText-primary": {
      fontWeight: 600,
      fontSize: 14,
      color: "#333",
    },
    "& .MuiListItemText-secondary": {
      fontSize: 12,
      color: "#999",
    },
  },
  avatar: {
    width: 38,
    height: 38,
    backgroundColor: "#f3e8f0",
    color: "#9a5188",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "Rubik, sans-serif",
    transition: "transform 0.3s ease",
  },
  deleteButton: {
    width: 34,
    height: 34,
    flexShrink: 0,
    color: "#b85c5c",
    backgroundColor: "#fff7f7",
    border: "1px solid #f1d4d4",
    transition: "all 0.25s ease",
    "&:hover": {
      color: "#e53935",
      backgroundColor: "#fff0f0",
      borderColor: "#e8bebe",
    },
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    color: "#bbb",
    fontFamily: "Rubik, sans-serif",
  },
  countBadge: {
    fontFamily: "Rubik, sans-serif",
    fontSize: 12,
    fontWeight: 600,
    color: "rgba(255,255,255,0.8)",
    marginTop: 2,
  },
});
