import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "calc(env(safe-area-inset-top, 0px) + 20px) 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#F7F7F8",
        animation: "fadeIn 0.4s ease-out",
    },
    header: {
        fontWeight: 700,
        fontSize: 22,
        marginBottom: 4,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInDown 0.5s ease-out",
    },
    subtitle: {
        fontSize: 13,
        color: "#6B7280",
        marginBottom: 24,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInDown 0.5s 0.1s ease-out both",
    },
    attendeeRow: {
        borderRadius: 20,
        padding: "14px 18px",
        backgroundColor: "#fff",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        marginBottom: 10,
        transition: "transform 0.18s ease, box-shadow 0.18s ease",
        animation: "fadeInUp 0.4s ease-out both",
        "&:active": { transform: "scale(0.98)" },
    },
    attendeeName: {
        fontWeight: 600,
        fontSize: 14,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    checkedIn: {
        backgroundColor: "#EAF7EE",
        boxShadow: "0 4px 12px rgba(47, 125, 50, 0.12)",
        borderRight: "4px solid #2F7D32",
    },
    saveButton: {
        borderRadius: 14,
        height: 50,
        fontWeight: 700,
        fontSize: 15,
        textTransform: "none" as const,
        marginTop: 24,
        fontFamily: "Rubik, sans-serif",
        boxShadow: "0 4px 12px rgba(123, 63, 152, 0.22)",
        transition: "all 0.3s ease",
        animation: "fadeInUp 0.6s ease-out both",
        "&:hover": {
            transform: "translateY(-2px)",
            boxShadow: "0 6px 16px rgba(123, 63, 152, 0.26)",
        },
        "&:active": { transform: "scale(0.98)" },
    },
    notesField: {
        "& .MuiOutlinedInput-root": {
            borderRadius: 14,
            transition: "box-shadow 0.3s ease",
            "&.Mui-focused": {
                boxShadow: "0 0 0 3px rgba(123, 63, 152, 0.12)",
            },
        },
    },
    loading: {
        textAlign: "center" as const,
        marginTop: 60,
        color: "#6B7280",
        animation: "pulse 1.5s ease-in-out infinite",
    },
    backButton: {
        marginBottom: 12,
        textTransform: "none" as const,
        fontWeight: 600,
        fontFamily: "Rubik, sans-serif",
        color: "#7B3F98",
        transition: "all 0.2s ease",
        "&:hover": { transform: "translateX(4px)" },
    },
});
