import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "88px 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#f9f9f9",
        animation: "fadeIn 0.4s ease-out",
    },
    avatarWrapper: {
        display: "flex",
        justifyContent: "center",
        marginBottom: 16,
        animation: "scaleIn 0.5s ease-out",
    },
    avatar: {
        width: 88,
        height: 88,
        background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
        fontSize: 34,
        fontWeight: 700,
        fontFamily: "Rubik, sans-serif",
        boxShadow: "0 6px 24px rgba(154, 81, 136, 0.3)",
        transition: "transform 0.3s ease, box-shadow 0.3s ease",
        "&:hover": {
            transform: "scale(1.08)",
            boxShadow: "0 10px 32px rgba(154, 81, 136, 0.4)",
        },
    },
    name: {
        fontWeight: 700,
        fontSize: 24,
        textAlign: "center" as const,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.5s 0.2s ease-out both",
    },
    role: {
        textAlign: "center" as const,
        color: "#9a5188",
        fontWeight: 600,
        fontSize: 14,
        marginBottom: 24,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.5s 0.3s ease-out both",
    },
    statsRow: {
        display: "flex",
        gap: 12,
        marginBottom: 24,
        animation: "fadeInUp 0.5s 0.4s ease-out both",
    },
    statCard: {
        flex: 1,
        borderRadius: 18,
        padding: 16,
        textAlign: "center" as const,
        backgroundColor: "#fff",
        boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
        transition: "all 0.3s cubic-bezier(0.4,0,0.2,1)",
        "&:hover": {
            transform: "translateY(-3px)",
            boxShadow: "0 8px 24px rgba(154,81,136,0.12)",
        },
        "&:active": { transform: "scale(0.97)" },
    },
    statValue: {
        fontWeight: 800,
        fontSize: 26,
        color: "#9a5188",
        fontFamily: "Rubik, sans-serif",
    },
    statLabel: {
        fontSize: 11,
        color: "#888",
        marginTop: 2,
        fontFamily: "Rubik, sans-serif",
    },
    section: {
        marginBottom: 20,
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 16,
        boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
        animation: "fadeInUp 0.5s 0.5s ease-out both",
        transition: "all 0.3s ease",
    },
    sectionTitle: {
        fontWeight: 700,
        fontSize: 15,
        marginBottom: 10,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
    },
    infoRow: {
        display: "flex",
        justifyContent: "space-between",
        padding: "12px 0",
        borderBottom: "1px solid #f5f0f3",
        transition: "background-color 0.2s ease",
        "&:hover": { backgroundColor: "#faf7f9" },
    },
    infoLabel: {
        fontSize: 13,
        color: "#999",
        fontFamily: "Rubik, sans-serif",
    },
    infoValue: {
        fontSize: 13,
        fontWeight: 600,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
    },
    logoutButton: {
        borderRadius: 14,
        height: 48,
        fontWeight: 700,
        fontSize: 15,
        textTransform: "none" as const,
        fontFamily: "Rubik, sans-serif",
        marginTop: 20,
        color: "#d32f2f",
        borderColor: "#d32f2f",
        transition: "all 0.3s ease",
        animation: "fadeInUp 0.5s 0.6s ease-out both",
        "&:hover": {
            borderColor: "#b71c1c",
            backgroundColor: "#fff5f5",
            transform: "translateY(-2px)",
            boxShadow: "0 4px 16px rgba(211, 47, 47, 0.15)",
        },
        "&:active": { transform: "scale(0.98)" },
    },
});
