import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding:
            "calc(env(safe-area-inset-top, 0px) + 16px) clamp(16px, 4vw, 28px) calc(var(--shell-bottom-inset, 0px) + env(safe-area-inset-bottom, 0px) + 24px)",
        maxWidth: 680,
        margin: "0 auto",
        minHeight: "100dvh",
        background:
            "linear-gradient(180deg, var(--color-canvas-warm, #faf9fb) 0%, var(--color-canvas, #f5f6f8) 100%)",
        fontFamily:
            '"Noto Sans Hebrew", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        animation: "fadeIn 220ms var(--ease-out, ease-out)",
        "@media (prefers-reduced-motion: reduce)": {
            animation: "fadeIn 1ms linear",
        },
    },
    topBar: {
        display: "grid",
        gridTemplateColumns: "1fr auto 1fr",
        alignItems: "center",
        marginBottom: 18,
    },
    backButton: {
        justifySelf: "start",
        minHeight: 44,
        color: "var(--color-primary)",
        fontWeight: 750,
        fontSize: 13,
        textTransform: "none" as const,
        fontFamily: "inherit",
        borderRadius: "var(--radius-md, 14px)",
        minWidth: 0,
        padding: "8px 12px",
        transition:
            "transform var(--transition-fast, 140ms ease), background-color var(--transition-fast, 140ms ease)",
        "&:hover": {
            backgroundColor: "var(--color-primary-soft)",
        },
        "&:active": {
            transform: "scale(0.98)",
        },
        "@media (prefers-reduced-motion: reduce)": {
            transition: "background-color 1ms linear",
            "&:active": {
                transform: "none",
            },
        },
    },
    pageTitle: {
        justifySelf: "center",
        fontWeight: 800,
        fontSize: 18,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
    },
    heroCard: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        borderRadius: "var(--radius-sheet, 26px)",
        padding: "26px 20px 22px",
        marginBottom: 14,
        backgroundColor: "var(--color-surface-elevated, rgba(255, 255, 255, 0.82))",
        border: "1px solid rgba(255, 255, 255, 0.72)",
        boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16, 24, 40, 0.07))",
        backdropFilter: "blur(20px) saturate(180%)",
        WebkitBackdropFilter: "blur(20px) saturate(180%)",
        animation: "fadeInUp 240ms var(--ease-out, ease-out) both",
        "@media (min-width: 700px)": {
            padding: "32px 24px 26px",
        },
        "@media (prefers-reduced-motion: reduce)": {
            animation: "none",
        },
        "@media (prefers-reduced-transparency: reduce)": {
            backgroundColor: "var(--color-surface, #fff)",
            backdropFilter: "none",
            WebkitBackdropFilter: "none",
            borderColor: "var(--color-border, #dadde3)",
        },
    },
    avatar: {
        width: 96,
        height: 96,
        backgroundColor: "var(--color-primary)",
        color: "#FFFFFF",
        fontSize: 38,
        fontWeight: 800,
        fontFamily: "inherit",
        boxShadow: "0 12px 30px rgba(var(--color-primary-rgb), 0.22)",
        marginBottom: 14,
    },
    name: {
        fontWeight: 800,
        fontSize: "clamp(24px, 5vw, 30px)",
        textAlign: "center" as const,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
        lineHeight: 1.2,
    },
    role: {
        textAlign: "center" as const,
        color: "var(--color-text-secondary, #51565c)",
        fontWeight: 700,
        fontSize: 14,
        marginTop: 6,
        fontFamily: "inherit",
    },
    branchPill: {
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        marginTop: 12,
        padding: "7px 12px",
        borderRadius: 999,
        color: "var(--color-primary)",
        backgroundColor: "var(--color-primary-soft)",
        fontWeight: 700,
        fontSize: 12,
        fontFamily: "inherit",
        "& .MuiTypography-root": {
            fontWeight: 700,
            fontSize: 12,
            fontFamily: "inherit",
        },
    },
    section: {
        marginBottom: 14,
        backgroundColor: "var(--color-surface-elevated, rgba(255, 255, 255, 0.82))",
        border: "1px solid rgba(255, 255, 255, 0.72)",
        borderRadius: "var(--radius-lg, 18px)",
        padding: 18,
        boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16, 24, 40, 0.07))",
        backdropFilter: "blur(18px) saturate(180%)",
        WebkitBackdropFilter: "blur(18px) saturate(180%)",
        animation: "fadeInUp 240ms var(--ease-out, ease-out) both",
        "@media (min-width: 700px)": {
            padding: 22,
        },
        "@media (prefers-reduced-motion: reduce)": {
            animation: "none",
        },
        "@media (prefers-reduced-transparency: reduce)": {
            backgroundColor: "var(--color-surface, #fff)",
            backdropFilter: "none",
            WebkitBackdropFilter: "none",
            borderColor: "var(--color-border, #dadde3)",
        },
    },
    sectionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginBottom: 12,
    },
    sectionTitle: {
        fontWeight: 800,
        fontSize: 15,
        marginBottom: 0,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
    },
    profileAlert: {
        marginBottom: 14,
        borderRadius: "16px !important",
        fontFamily: "inherit !important",
    },
    infoRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        padding: "12px 0",
        borderBottom: "1px solid var(--color-border-subtle, #e9ebef)",
        "&:last-child": {
            borderBottom: "none",
            paddingBottom: 0,
        },
    },
    infoLabelWrap: {
        display: "flex",
        alignItems: "center",
        gap: 9,
        minWidth: 0,
    },
    infoIcon: {
        width: 30,
        height: 30,
        borderRadius: "50%",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: "var(--color-primary)",
        backgroundColor: "var(--color-primary-soft)",
    },
    infoLabel: {
        fontSize: 13,
        color: "var(--color-text-secondary, #51565c)",
        fontWeight: 700,
        fontFamily: "inherit",
        whiteSpace: "nowrap" as const,
    },
    infoValue: {
        fontSize: 13,
        fontWeight: 700,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
        textAlign: "left" as const,
        overflowWrap: "anywhere" as const,
        lineHeight: 1.45,
    },
    infoValueWrap: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 6,
        minWidth: 0,
    },
    inlineEditButton: {
        width: 44,
        height: 44,
        color: "var(--color-text-secondary, #51565c)",
        backgroundColor: "transparent",
        "&:hover": {
            backgroundColor: "var(--color-surface-muted, #f0f2f4)",
        },
    },
    editFields: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 14,
        paddingTop: 4,
    },
    traineeRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        padding: "12px 0",
        minHeight: 56,
        borderBottom: "1px solid var(--color-border-subtle, #e9ebef)",
        cursor: "pointer",
        transition:
            "background-color var(--transition-fast, 140ms ease), transform var(--transition-fast, 140ms ease)",
        "&:focus-visible": {
            outline: "none",
            boxShadow: "var(--shadow-focus, 0 0 0 3px rgba(var(--color-primary-rgb), 0.20))",
            borderRadius: "var(--radius-md, 14px)",
        },
        "&:hover": {
            backgroundColor: "var(--color-canvas-warm, #faf9fb)",
        },
        "&:active": {
            transform: "scale(0.99)",
        },
        "@media (prefers-reduced-motion: reduce)": {
            transition: "background-color 1ms linear",
            "&:active": {
                transform: "none",
            },
        },
    },
    traineeRowText: {
        minWidth: 0,
    },
    traineeRowTitle: {
        fontSize: 13,
        fontWeight: 800,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
    },
    traineeRowMeta: {
        marginTop: 2,
        fontSize: 12,
        color: "var(--color-text-muted, #6e737a)",
        fontFamily: "inherit",
    },
    traineeChevron: {
        color: "var(--color-text-muted, #6e737a)",
        flexShrink: 0,
    },
    dialogTitle: {
        position: "relative" as const,
        textAlign: "center" as const,
        color: "var(--color-text, #1d1d1f)",
        fontWeight: "800 !important" as const,
        fontFamily: "inherit !important",
        padding: "18px 48px 10px !important",
    },
    dialogCloseButton: {
        position: "absolute" as const,
        left: 10,
        top: 10,
        width: 44,
        height: 44,
        color: "var(--color-text-secondary, #51565c)",
    },
    dialogActions: {
        padding: "8px 20px 18px !important",
        gap: "8px",
        "& .MuiButton-root": {
            borderRadius: 14,
            fontWeight: 800,
            textTransform: "none" as const,
            fontFamily: "inherit",
            minHeight: 44,
        },
        "& .MuiButton-contained": {
            backgroundColor: "var(--color-primary)",
            boxShadow: "var(--shadow-sm, 0 3px 12px rgba(16, 24, 40, 0.07))",
            "&:hover": {
                backgroundColor: "var(--color-primary-dark)",
            },
        },
    },
    dialogHero: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        padding: "8px 0 14px",
    },
    dialogAvatar: {
        width: 68,
        height: 68,
        backgroundColor: "var(--color-primary-soft)",
        color: "var(--color-primary)",
        fontSize: 26,
        fontWeight: 800,
        fontFamily: "inherit",
        marginBottom: 10,
    },
    dialogName: {
        fontSize: 18,
        fontWeight: 800,
        color: "var(--color-text, #1d1d1f)",
        fontFamily: "inherit",
    },
    logoutButton: {
        borderRadius: "var(--radius-md, 14px)",
        minHeight: 50,
        fontWeight: 800,
        fontSize: 15,
        textTransform: "none" as const,
        fontFamily: "inherit",
        marginTop: 6,
        color: "var(--color-danger, #b42318)",
        borderColor: "rgba(180, 35, 24, 0.24)",
        backgroundColor: "var(--color-surface, #fff)",
        boxShadow: "none",
        "&:hover": {
            borderColor: "rgba(180, 35, 24, 0.36)",
            backgroundColor: "var(--color-danger-soft, #fff1f0)",
            boxShadow: "none",
        },
        "&:active": { transform: "scale(0.98)" },
        "@media (prefers-reduced-motion: reduce)": {
            "&:active": {
                transform: "none",
            },
        },
    },
});
