import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "calc(env(safe-area-inset-top, 0px) + 16px) 16px 96px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#F7F7F8",
    },
    topBar: {
        display: "grid",
        gridTemplateColumns: "1fr auto 1fr",
        alignItems: "center",
        marginBottom: 16,
    },
    backButton: {
        justifySelf: "start",
        color: "#7B3F98",
        fontWeight: 700,
        fontSize: 13,
        textTransform: "none" as const,
        fontFamily: "Rubik, sans-serif",
        borderRadius: 999,
        minWidth: 0,
        padding: "6px 10px",
        "&:hover": {
            backgroundColor: "#F3EAF7",
        },
    },
    pageTitle: {
        justifySelf: "center",
        fontWeight: 800,
        fontSize: 18,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    heroCard: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        borderRadius: 24,
        padding: "26px 20px 22px",
        marginBottom: 14,
        backgroundColor: "#FFFFFF",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
    },
    avatar: {
        width: 96,
        height: 96,
        backgroundColor: "#7B3F98",
        color: "#FFFFFF",
        fontSize: 38,
        fontWeight: 800,
        fontFamily: "Rubik, sans-serif",
        boxShadow: "0 8px 18px rgba(123, 63, 152, 0.22)",
        marginBottom: 14,
    },
    name: {
        fontWeight: 800,
        fontSize: 24,
        textAlign: "center" as const,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        lineHeight: 1.2,
    },
    role: {
        textAlign: "center" as const,
        color: "#6B7280",
        fontWeight: 700,
        fontSize: 14,
        marginTop: 6,
        fontFamily: "Rubik, sans-serif",
    },
    branchPill: {
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        marginTop: 12,
        padding: "7px 12px",
        borderRadius: 999,
        color: "#7B3F98",
        backgroundColor: "#F3EAF7",
        fontWeight: 700,
        fontSize: 12,
        fontFamily: "Rubik, sans-serif",
        "& .MuiTypography-root": {
            fontWeight: 700,
            fontSize: 12,
            fontFamily: "Rubik, sans-serif",
        },
    },
    section: {
        marginBottom: 14,
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 18,
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
    },
    sectionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginBottom: 12,
    },
    sectionTitle: {
        fontWeight: 800,
        fontSize: 15,
        marginBottom: 0,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    profileAlert: {
        marginBottom: 14,
        borderRadius: "16px !important",
        fontFamily: "Rubik, sans-serif !important",
    },
    infoRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        padding: "12px 0",
        borderBottom: "1px solid #F1F2F4",
        "&:last-child": {
            borderBottom: "none",
            paddingBottom: 0,
        },
    },
    infoLabelWrap: {
        display: "flex",
        alignItems: "center",
        gap: 9,
        minWidth: 0,
    },
    infoIcon: {
        width: 30,
        height: 30,
        borderRadius: "50%",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: "#7B3F98",
        backgroundColor: "#F3EAF7",
    },
    infoLabel: {
        fontSize: 13,
        color: "#6B7280",
        fontWeight: 700,
        fontFamily: "Rubik, sans-serif",
        whiteSpace: "nowrap" as const,
    },
    infoValue: {
        fontSize: 13,
        fontWeight: 700,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        textAlign: "left" as const,
        overflowWrap: "anywhere" as const,
        lineHeight: 1.45,
    },
    infoValueWrap: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 6,
        minWidth: 0,
    },
    inlineEditButton: {
        width: 30,
        height: 30,
        color: "#6B7280",
        backgroundColor: "transparent",
        "&:hover": {
            backgroundColor: "#F1F2F4",
        },
    },
    editFields: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 14,
        paddingTop: 4,
    },
    traineeRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        padding: "12px 0",
        borderBottom: "1px solid #F1F2F4",
        cursor: "pointer",
        transition: "background-color 0.18s ease, transform 0.18s ease",
        "&:hover": {
            backgroundColor: "#FAFAFB",
        },
        "&:active": {
            transform: "scale(0.99)",
        },
    },
    traineeRowText: {
        minWidth: 0,
    },
    traineeRowTitle: {
        fontSize: 13,
        fontWeight: 800,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    traineeRowMeta: {
        marginTop: 2,
        fontSize: 12,
        color: "#6B7280",
        fontFamily: "Rubik, sans-serif",
    },
    traineeChevron: {
        color: "#9CA3AF",
        flexShrink: 0,
    },
    dialogTitle: {
        position: "relative" as const,
        textAlign: "center" as const,
        color: "#1F1F1F",
        fontWeight: "800 !important" as const,
        fontFamily: "Rubik, sans-serif !important",
        padding: "18px 48px 10px !important",
    },
    dialogCloseButton: {
        position: "absolute" as const,
        left: 10,
        top: 10,
        color: "#6B7280",
    },
    dialogActions: {
        padding: "8px 20px 18px !important",
        gap: "8px",
        "& .MuiButton-root": {
            borderRadius: 14,
            fontWeight: 800,
            textTransform: "none" as const,
            fontFamily: "Rubik, sans-serif",
        },
        "& .MuiButton-contained": {
            backgroundColor: "#7B3F98",
            boxShadow: "0 4px 12px rgba(123, 63, 152, 0.22)",
            "&:hover": {
                backgroundColor: "#6D3588",
            },
        },
    },
    dialogHero: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        padding: "8px 0 14px",
    },
    dialogAvatar: {
        width: 68,
        height: 68,
        backgroundColor: "#F3EAF7",
        color: "#7B3F98",
        fontSize: 26,
        fontWeight: 800,
        fontFamily: "Rubik, sans-serif",
        marginBottom: 10,
    },
    dialogName: {
        fontSize: 18,
        fontWeight: 800,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    logoutButton: {
        borderRadius: 16,
        height: 48,
        fontWeight: 800,
        fontSize: 15,
        textTransform: "none" as const,
        fontFamily: "Rubik, sans-serif",
        marginTop: 6,
        color: "#B42318",
        borderColor: "#F7D4D6",
        backgroundColor: "#FFFFFF",
        boxShadow: "none",
        "&:hover": {
            borderColor: "#F1B8BC",
            backgroundColor: "#FCEEEF",
            boxShadow: "none",
        },
        "&:active": { transform: "scale(0.98)" },
    },
});
