import { makeStyles } from "@mui/styles";

export const useCardStyles = makeStyles({
  cardContainer: {
    width: "100%",
  },
  card: {
    direction: "rtl" as const,
    height: "100%",
    display: "flex",
    flexDirection: "column" as const,
    borderRadius: 12,
    border: "1px solid #eee6ec",
    backgroundColor: "#fff",
    boxShadow: "0 8px 24px rgba(45, 35, 43, 0.08)",
    overflow: "hidden",
    transition: "transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease",
    animation: "fadeInUp 0.5s ease-out both",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 14px 30px rgba(45, 35, 43, 0.11)",
      borderColor: "#dcc7d6",
    },
  },
  cardContent: {
    flex: 1,
    padding: "16px 16px 12px",
    fontFamily: "Rubik, sans-serif",
  },
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 14,
  },
  titleBlock: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  eventName: {
    minWidth: 0,
    fontWeight: 800,
    fontFamily: "Rubik, sans-serif",
    fontSize: "1.12rem",
    lineHeight: 1.3,
    color: "#262026",
    overflowWrap: "anywhere" as const,
  },
  editButton: {
    flexShrink: 0,
    width: 34,
    height: 34,
    color: "#7a3e6b",
    backgroundColor: "#fbf7fa",
    border: "1px solid #ead8e5",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "#fff",
      backgroundColor: "#9a5188",
      borderColor: "#9a5188",
    },
  },
  typeChip: {
    flexShrink: 0,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#f5ecf2",
    color: "#7a3e6b",
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "Rubik, sans-serif",
    border: "1px solid #ead8e5",
  },
  detailsList: {
    marginBottom: 4,
  },
  detailRow: {
    display: "grid",
    gridTemplateColumns: "22px minmax(0, 1fr)",
    gap: 9,
    alignItems: "center",
    minHeight: 26,
  },
  detailIcon: {
    color: "#9a5188",
    fontSize: 19,
  },
  detailValue: {
    color: "#2f2930",
    fontSize: 13.5,
    fontWeight: 700,
    lineHeight: 1.45,
    fontFamily: "Rubik, sans-serif",
    overflowWrap: "anywhere" as const,
  },
  description: {
    color: "#5f5660",
    fontSize: 13,
    lineHeight: 1.5,
    fontFamily: "Rubik, sans-serif",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  divider: {
    borderColor: "#f0e8ee",
  },
  cardActions: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "flex-start",
    gap: 8,
    padding: "11px 14px 13px",
  },
  showButton: {
    minHeight: 34,
    borderRadius: 8,
    fontWeight: 700,
    textTransform: "none" as const,
    fontFamily: "Rubik, sans-serif",
    fontSize: 12.5,
    backgroundColor: "#9a5188",
    color: "#fff",
    padding: "6px 10px",
    boxShadow: "none",
    "& .MuiButton-startIcon": {
      marginLeft: 5,
      marginRight: 0,
      "& svg": {
        fontSize: 18,
      },
    },
    "&:hover": {
      backgroundColor: "#7a3e6b",
      boxShadow: "0 4px 12px rgba(154, 81, 136, 0.22)",
    },
  },
  secondaryButton: {
    minHeight: 34,
    borderRadius: 8,
    fontWeight: 700,
    textTransform: "none" as const,
    fontFamily: "Rubik, sans-serif",
    fontSize: 12.5,
    backgroundColor: "#fff",
    color: "#6d3860",
    border: "1px solid #e7d8e2",
    padding: "6px 10px",
    "& .MuiButton-startIcon": {
      marginLeft: 5,
      marginRight: 0,
      "& svg": {
        fontSize: 18,
      },
    },
    "&:hover": {
      backgroundColor: "#fbf7fa",
      borderColor: "#d7bfd0",
    },
  },
});
