import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "calc(env(safe-area-inset-top, 0px) + 20px) 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#F7F7F8",
        animation: "fadeIn 0.4s ease-out",
    },
    header: {
        fontWeight: 700,
        fontSize: 22,
        marginBottom: 16,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInDown 0.5s ease-out",
    },
    traineeCard: {
        borderRadius: 20,
        padding: 18,
        backgroundColor: "#fff",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        marginBottom: 12,
        transition: "transform 0.18s ease, box-shadow 0.18s ease",
        animation: "fadeInUp 0.5s ease-out both",
        "&:active": { transform: "scale(0.98)" },
        "&:hover": {
            transform: "translateY(-3px)",
            boxShadow: "0 8px 18px rgba(0, 0, 0, 0.08)",
        },
    },
    traineeName: {
        fontWeight: 700,
        fontSize: 15,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    traineeInfo: {
        fontSize: 12,
        color: "#6B7280",
        marginTop: 2,
        fontFamily: "Rubik, sans-serif",
    },
    avatar: {
        width: 44,
        height: 44,
        backgroundColor: "#F3EAF7",
        color: "#7B3F98",
        fontWeight: 700,
        fontSize: 16,
        fontFamily: "Rubik, sans-serif",
        transition: "transform 0.3s ease",
        "&:hover": { transform: "scale(1.1)" },
    },
    actionButton: {
        minWidth: 38,
        width: 38,
        height: 38,
        borderRadius: 12,
        padding: 0,
        backgroundColor: "#F3EAF7",
        transition: "all 0.25s ease",
        "&:hover": {
            backgroundColor: "#EADAF2",
            transform: "scale(1.1)",
        },
        "&:active": { transform: "scale(0.95)" },
    },
    empty: {
        textAlign: "center" as const,
        color: "#6B7280",
        marginTop: 60,
        fontSize: 15,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeIn 0.6s ease-out",
    },
});
