import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "88px 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#f9f9f9",
        animation: "fadeIn 0.4s ease-out",
    },
    header: {
        fontWeight: 700,
        fontSize: 22,
        marginBottom: 16,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInDown 0.5s ease-out",
    },
    traineeCard: {
        borderRadius: 18,
        padding: 16,
        backgroundColor: "#fff",
        border: "1px solid #f0ecef",
        boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
        marginBottom: 10,
        transition: "all 0.3s cubic-bezier(0.4,0,0.2,1)",
        animation: "fadeInUp 0.5s ease-out both",
        "&:active": { transform: "scale(0.98)" },
        "&:hover": {
            transform: "translateY(-3px)",
            boxShadow: "0 8px 24px rgba(154,81,136,0.1)",
        },
    },
    traineeName: {
        fontWeight: 700,
        fontSize: 15,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
    },
    traineeInfo: {
        fontSize: 12,
        color: "#999",
        marginTop: 2,
        fontFamily: "Rubik, sans-serif",
    },
    avatar: {
        width: 44,
        height: 44,
        backgroundColor: "#9a5188",
        fontWeight: 700,
        fontSize: 16,
        fontFamily: "Rubik, sans-serif",
        transition: "transform 0.3s ease",
        "&:hover": { transform: "scale(1.1)" },
    },
    actionButton: {
        minWidth: 38,
        width: 38,
        height: 38,
        borderRadius: 12,
        padding: 0,
        backgroundColor: "#f8f4f9",
        transition: "all 0.25s ease",
        "&:hover": {
            backgroundColor: "#f0e8ee",
            transform: "scale(1.1)",
        },
        "&:active": { transform: "scale(0.95)" },
    },
    empty: {
        textAlign: "center" as const,
        color: "#bbb",
        marginTop: 60,
        fontSize: 15,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeIn 0.6s ease-out",
    },
});
