import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "88px 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#f9f9f9",
        animation: "fadeIn 0.35s ease-out",
    },
    greeting: {
        fontWeight: 700,
        fontSize: 24,
        marginBottom: 4,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.4s ease-out",
    },
    subtitle: {
        color: "#888",
        fontSize: 14,
        marginBottom: 20,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.5s ease-out",
    },
    nextEventCard: {
        borderRadius: 22,
        padding: 24,
        background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
        color: "#fff",
        marginBottom: 20,
        boxShadow: "0 8px 32px rgba(154, 81, 136, 0.3)",
        animation: "fadeInUp 0.55s ease-out",
        transition: "transform 0.3s cubic-bezier(0.4,0,0.2,1), box-shadow 0.3s ease",
        "&:active": {
            transform: "scale(0.98)",
        },
    },
    nextEventTitle: {
        fontWeight: 700,
        fontSize: 18,
        marginBottom: 10,
        fontFamily: "Rubik, sans-serif",
    },
    nextEventDetail: {
        fontSize: 13,
        opacity: 0.9,
        marginBottom: 4,
        fontFamily: "Rubik, sans-serif",
    },
    rsvpButtons: {
        display: "flex",
        gap: 8,
        marginTop: 14,
    },
    statsGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 12,
        marginBottom: 24,
    },
    statCard: {
        borderRadius: 18,
        padding: 20,
        textAlign: "center",
        backgroundColor: "#fff",
        boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
        border: "1px solid #f0ecef",
        animation: "fadeInUp 0.6s ease-out both",
        transition: "transform 0.25s cubic-bezier(0.4,0,0.2,1), box-shadow 0.25s ease",
        "&:active": {
            transform: "scale(0.97)",
        },
    },
    statValue: {
        fontWeight: 800,
        fontSize: 28,
        color: "#9a5188",
        fontFamily: "Rubik, sans-serif",
    },
    statLabel: {
        fontSize: 12,
        color: "#888",
        marginTop: 4,
        fontFamily: "Rubik, sans-serif",
    },
    sectionTitle: {
        fontWeight: 700,
        fontSize: 16,
        marginBottom: 10,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.65s ease-out",
    },
    eventItem: {
        borderRadius: 16,
        padding: 16,
        marginBottom: 8,
        backgroundColor: "#fff",
        boxShadow: "0 2px 10px rgba(0,0,0,0.04)",
        border: "1px solid #f0ecef",
        transition: "all 0.25s cubic-bezier(0.4,0,0.2,1)",
        animation: "fadeInUp 0.5s ease-out both",
        "&:active": {
            transform: "scale(0.98)",
            boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
        },
    },
    eventItemName: {
        fontWeight: 700,
        fontSize: 14,
        color: "#333",
        fontFamily: "Rubik, sans-serif",
    },
    eventItemDate: {
        fontSize: 12,
        color: "#999",
        marginTop: 2,
        fontFamily: "Rubik, sans-serif",
    },
    typeChip: {
        fontSize: 11,
        height: 24,
        borderRadius: 10,
        backgroundColor: "#f3e8f0",
        color: "#9a5188",
        transition: "background 0.2s ease",
    },
});
