import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
    root: {
        direction: "rtl",
        padding: "calc(env(safe-area-inset-top, 0px) + 20px) 16px 90px",
        maxWidth: 520,
        margin: "0 auto",
        minHeight: "100vh",
        backgroundColor: "#F7F7F8",
        animation: "fadeIn 0.35s ease-out",
    },
    greeting: {
        fontWeight: 700,
        fontSize: 25,
        marginBottom: 6,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.4s ease-out",
    },
    subtitle: {
        color: "#6B7280",
        fontSize: 14,
        fontFamily: "Rubik, sans-serif",
        animation: "fadeInUp 0.5s ease-out",
    },
    headerRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginBottom: 22,
    },
    profileButton: {
        minWidth: 0,
        padding: 4,
        borderRadius: "50%",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        transition: "transform 0.18s ease, box-shadow 0.18s ease",
        "&:hover": {
            backgroundColor: "#FFFFFF",
            boxShadow: "0 8px 18px rgba(0, 0, 0, 0.08)",
        },
        "&:active": {
            transform: "scale(0.96)",
        },
    },
    profileAvatar: {
        width: 44,
        height: 44,
        backgroundColor: "#F3EAF7",
        color: "#7B3F98",
        fontWeight: 800,
        fontFamily: "Rubik, sans-serif",
    },
    eventCarousel: {
        marginBottom: 20,
    },
    eventCarouselRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
    },
    eventCarouselCard: {
        minWidth: 0,
        flex: 1,
    },
    eventCarouselArrow: {
        width: 36,
        height: 36,
        flexShrink: 0,
        color: "#7B3F98",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        "&:hover": {
            backgroundColor: "#F3EAF7",
        },
        "&.Mui-disabled": {
            color: "#CBD0D6",
            backgroundColor: "#FFFFFF",
            boxShadow: "none",
        },
    },
    eventCarouselIndicator: {
        textAlign: "center" as const,
        marginTop: 8,
        fontSize: 12,
        fontWeight: 700,
        color: "#6B7280",
        fontFamily: "Rubik, sans-serif",
    },
    eventItem: {
        borderRadius: 20,
        padding: 20,
        marginBottom: 14,
        backgroundColor: "#fff",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        transition: "transform 0.18s ease, box-shadow 0.18s ease",
        animation: "fadeInUp 0.5s ease-out both",
        "&:active": {
            transform: "scale(0.98)",
        },
    },
    eventItemName: {
        fontWeight: 700,
        fontSize: 15,
        color: "#1F1F1F",
        fontFamily: "Rubik, sans-serif",
    },
    eventItemDate: {
        fontSize: 12,
        color: "#6B7280",
        marginTop: 4,
        fontFamily: "Rubik, sans-serif",
    },
    typeChip: {
        fontSize: 11,
        height: 24,
        borderRadius: 999,
        backgroundColor: "#F3EAF7",
        color: "#7B3F98",
        transition: "background 0.2s ease",
    },
});
