import { makeStyles } from "@mui/styles";

export const useNavbarStyles = makeStyles({
  appBar: {
    background: "var(--color-primary)",
    backdropFilter: "blur(22px) saturate(180%)",
    WebkitBackdropFilter: "blur(22px) saturate(180%)",
    borderBottom: "1px solid rgba(255, 255, 255, 0.18)",
    boxShadow: "0 12px 32px rgba(45, 35, 43, 0.16)",
    color: "var(--color-surface)",
    zIndex: 1250,
    paddingTop: "env(safe-area-inset-top, 0px)",
    animation: "fadeInDown var(--transition-slow, 240ms cubic-bezier(0.32, 0.72, 0, 1))",
    overflowX: "clip" as const,
  },
  toolbar: {
    position: "relative" as const,
    justifyContent: "space-between",
    paddingInline: "24px !important",
    minHeight: 64,
  },
  title: {
    flexGrow: 1,
    textAlign: "center" as const,
    fontFamily: "inherit",
    fontWeight: 700,
    letterSpacing: 0,
    fontSize: "1.8rem",
    paddingInlineEnd: "8%",
    textShadow: "0 2px 4px rgba(0,0,0,0.15)",
  },
  navbarLogoSlot: {
    position: "absolute" as const,
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    maxWidth: "min(320px, 42vw)",
    pointerEvents: "none" as const,
  },
  navbarLogo: {
    display: "block",
    maxHeight: 54,
    maxWidth: "100%",
    width: "auto",
    height: "auto",
    objectFit: "contain" as const,
    transform: "scale(1.18)",
    transformOrigin: "center",
  },
  userInfo: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    gap: 8,
    maxWidth: 210,
    backgroundColor: "transparent",
    border: "1px solid transparent",
    borderRadius: "999px !important",
    padding: "3px 8px 3px 4px",
    marginInlineEnd: 8,
    minHeight: 44,
    lineHeight: 1.3,
    cursor: "pointer",
    transition:
      "background-color 180ms ease, border-color 180ms ease, transform 120ms ease",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.12)",
      borderColor: "rgba(255, 255, 255, 0.24)",
    },
    "&:focus-visible": {
      outline: "2px solid rgba(255, 255, 255, 0.9)",
      outlineOffset: 3,
      backgroundColor: "rgba(255, 255, 255, 0.14)",
    },
    "&:active": {
      transform: "scale(0.98)",
    },
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: "var(--color-surface)",
    color: "var(--color-primary)",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.2)",
    fontFamily: "inherit",
    fontWeight: 800,
    fontSize: "0.9rem",
  },
  userName: {
    fontFamily: "inherit",
    fontWeight: 700,
    fontSize: "0.9rem",
    color: "var(--color-surface)",
    lineHeight: 1.4,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    zIndex: 1,
  },
  menuIconBox: {
    width: "44px !important",
    height: "44px !important",
    borderRadius: "12px !important",
    color: "var(--color-surface) !important",
    backgroundColor: "transparent !important",
    transition:
      "background-color 180ms ease, transform 120ms ease !important",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.14) !important",
    },
    "&:active": {
      transform: "scale(0.96)",
    },
    "&:focus-visible": {
      outline: "2px solid rgba(255, 255, 255, 0.9)",
      outlineOffset: 3,
    },
  },
  homeButton: {
    width: 44,
    height: 44,
    color: "var(--color-surface)",
    borderRadius: "12px !important",
    transition:
      "background-color 180ms ease, transform 120ms ease !important",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.14)",
    },
    "&:active": {
      transform: "scale(0.95)",
    },
  },
  profileDialogTitle: {
    position: "relative" as const,
    padding: "18px 24px 10px !important",
    fontFamily: "inherit !important",
    fontWeight: "800 !important" as const,
    color: "#2f2930",
  },
  profileDialogClose: {
    position: "absolute" as const,
    left: "12px !important",
    top: "12px !important",
    color: "#6b6068 !important",
  },
  profileDialogPaper: {
    direction: "rtl" as const,
    borderRadius: "var(--radius-xl, 22px) !important",
    border: "1px solid var(--color-border-subtle)",
    backgroundColor: "var(--color-surface)",
    overflow: "hidden",
  },
  profileTitle: {
    position: "relative" as const,
    padding: "18px 24px 14px !important",
    paddingInlineEnd: "64px !important",
    fontFamily: "inherit !important",
    fontWeight: "800 !important" as const,
    fontSize: "1.12rem !important",
    color: "var(--color-brand-ink)",
    borderBottom: "1px solid var(--color-border-subtle)",
  },
  profileClose: {
    position: "absolute" as const,
    left: "10px !important",
    top: "8px !important",
    width: "44px !important",
    height: "44px !important",
    color: "var(--color-primary) !important",
    backgroundColor: "var(--color-primary-soft) !important",
    border: "1px solid var(--color-primary-border) !important",
    "&:hover": {
      backgroundColor: "var(--color-primary-selected) !important",
    },
  },
  profileContent: {
    padding: "16px 20px !important",
  },
  profileLoading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 220,
  },
  profileBody: {
    gap: "12px !important",
  },
  profileHero: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px",
    borderRadius: "var(--radius-md, 14px)",
    backgroundColor: "var(--color-primary-soft)",
    border: "1px solid var(--color-primary-border)",
  },
  profileAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-primary)",
    color: "#fff",
    fontFamily: "inherit",
    fontWeight: 800,
    fontSize: "1.15rem",
    flexShrink: 0,
  },
  profileName: {
    fontFamily: "inherit",
    fontWeight: "800 !important" as const,
    color: "var(--color-brand-ink)",
    fontSize: "1.08rem",
  },
  profileMeta: {
    marginTop: "2px !important",
    fontFamily: "inherit",
    color: "var(--color-text-secondary)",
    fontSize: "0.86rem !important",
  },
  profileInfoList: {
    overflow: "hidden",
    borderRadius: "var(--radius-md, 14px)",
    border: "1px solid var(--color-border-subtle)",
    backgroundColor: "var(--color-surface)",
    "& > *:not(:last-child)": {
      borderBottom: "1px solid var(--color-border-subtle)",
    },
  },
  profileInfoRow: {
    display: "grid",
    gridTemplateColumns: "100px minmax(0, 1fr)",
    alignItems: "center",
    gap: 12,
    minHeight: 44,
    padding: "9px 12px",
  },
  profileInfoLabel: {
    color: "var(--color-text-secondary)",
    fontFamily: "inherit !important",
    fontSize: "0.82rem !important",
    fontWeight: "600 !important" as const,
  },
  profileInfoValue: {
    minWidth: 0,
    color: "var(--color-text)",
    fontFamily: "inherit !important",
    fontSize: "0.88rem !important",
    fontWeight: "700 !important" as const,
    textAlign: "start" as const,
    overflowWrap: "anywhere" as const,
    unicodeBidi: "plaintext" as const,
  },
  profileActions: {
    flexDirection: "column" as const,
    alignItems: "stretch !important",
    gap: "10px !important",
    padding: "12px 20px 18px !important",
    borderTop: "1px solid var(--color-border-subtle)",
  },
  profileBranchAction: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minWidth: 0,
    minHeight: 52,
    padding: "6px 10px 6px 6px",
    borderRadius: "var(--radius-md, 14px)",
    border: "1px solid var(--color-border-subtle)",
    backgroundColor: "var(--color-surface-muted)",
  },
  profileBranchLabel: {
    fontFamily: "inherit",
    fontWeight: "700 !important" as const,
    color: "var(--color-text-secondary)",
    fontSize: "0.84rem !important",
    whiteSpace: "nowrap" as const,
  },
  profileAccountActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
  },
  profileActionButton: {
    borderRadius: "10px !important",
    fontFamily: "inherit !important",
    fontWeight: "700 !important" as const,
    minHeight: "44px !important",
    flex: "1 1 0",
  },
  "@media (max-width: 640px)": {
    toolbar: {
      minHeight: 58,
      paddingInline: "8px !important",
    },
    navbarLogoSlot: {
      maxWidth: "min(160px, 30vw)",
    },
    navbarLogo: {
      maxHeight: 38,
      transform: "none",
    },
    profileAccountActions: {
      justifyContent: "space-between",
    },
    userInfo: {
      maxWidth: 112,
      gap: 6,
      padding: "2px 5px 2px 3px",
      marginInlineEnd: 2,
      minHeight: 40,
    },
    userAvatar: {
      width: 34,
      height: 34,
      fontSize: "0.82rem",
    },
    userName: {
      maxWidth: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap" as const,
    },
    profileDialogPaper: {
      width: "calc(100% - 24px)",
      margin: "12px !important",
      maxHeight: "calc(100dvh - 24px)",
    },
    profileContent: {
      padding: "14px !important",
    },
    profileActions: {
      padding: "12px 14px 14px !important",
    },
    profileInfoRow: {
      gridTemplateColumns: "88px minmax(0, 1fr)",
      gap: 8,
      paddingInline: 10,
    },
    navActions: {
      gap: 4,
    },
    homeButton: {
      width: 40,
      height: 40,
    },
    menuIconBox: {
      width: "40px !important",
      height: "40px !important",
    },
  },
  "@media (max-width: 420px)": {
    profileBranchAction: {
      flexDirection: "column" as const,
      alignItems: "stretch",
      padding: 10,
    },
    profileAccountActions: {
      flexDirection: "column" as const,
    },
    profileInfoRow: {
      gridTemplateColumns: "82px minmax(0, 1fr)",
    },
  },
  "@media (prefers-reduced-motion: reduce)": {
    appBar: {
      animation: "none",
    },
    userInfo: {
      transition: "background-color 120ms ease, border-color 120ms ease",
    },
    menuIconBox: {
      transition: "background-color 120ms ease !important",
      "&:active": {
        transform: "none",
      },
    },
    homeButton: {
      transition: "background-color 120ms ease !important",
      "&:active": {
        transform: "none",
      },
    },
  },
  "@media (prefers-reduced-transparency: reduce)": {
    appBar: {
      background: "var(--color-primary)",
      backdropFilter: "none",
      WebkitBackdropFilter: "none",
    },
    userInfo: {
      backdropFilter: "none",
      WebkitBackdropFilter: "none",
    },
  },
});
