import { makeStyles } from "@mui/styles";

export const useVolunteerDetailsStyles = makeStyles({
  panel: {
    flex: "0 0 clamp(340px, 31vw, 440px)",
    minWidth: 0,
    maxHeight: "calc(100vh - 250px)",
    borderRadius: 18,
    overflow: "hidden",
    boxShadow: "0 10px 30px rgba(45, 35, 43, 0.11)",
    fontFamily: "Rubik, sans-serif",
    direction: "rtl",
    backgroundColor: "#fff",
    border: "1px solid #efe5ed",
    animation: "fadeInUp 0.25s ease-out",
  },
  header: {
    padding: "18px 18px 16px",
    background:
      "linear-gradient(180deg, #ffffff 0%, #fbf7fa 100%)",
    color: "#2f2930",
    borderBottom: "1px solid #eee3eb",
  },
  closeIconButton: {
    color: "#7a3e6b",
    backgroundColor: "#fff",
    border: "1px solid #ead8e5",
    width: 38,
    height: 38,
    flexShrink: 0,
    "&:hover": {
      backgroundColor: "#9a5188",
      color: "#fff",
      borderColor: "#9a5188",
    },
  },
  avatar: {
    width: 56,
    height: 56,
    backgroundColor: "#f2e6ee",
    color: "#7a3e6b",
    fontWeight: 900,
    fontSize: 18,
    fontFamily: "Rubik, sans-serif",
    border: "1px solid #ead8e5",
    boxShadow: "0 6px 18px rgba(122, 62, 107, 0.12)",
  },
  nameText: {
    fontWeight: "900 !important" as const,
    fontFamily: "Rubik, sans-serif",
    color: "#2f2930",
    lineHeight: "1.25 !important" as const,
    maxWidth: "100%",
  },
  entityChip: {
    height: 24,
    width: "fit-content",
    marginTop: "6px !important",
    backgroundColor: "#f7edf4",
    color: "#7a3e6b",
    border: "1px solid #ead8e5",
    fontFamily: "Rubik, sans-serif",
    fontWeight: "800 !important" as const,
    fontSize: "0.74rem !important",
  },
  headerMeta: {
    marginTop: "8px !important",
    flexWrap: "wrap" as const,
    rowGap: 6,
  },
  nationalIdActions: {
    flexShrink: 0,
    padding: "2px",
    borderRadius: 999,
    backgroundColor: "#fff",
    border: "1px solid #f0e6ee",
  },
  nationalIdActionButton: {
    minWidth: "auto",
    padding: "2px 7px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    fontFamily: "Rubik, sans-serif",
    color: "#7a3e6b",
    "&:hover": {
      backgroundColor: "#f2e6ee",
    },
  },
  nationalIdStatus: {
    display: "block",
    marginTop: 6,
    color: "#7a3e6b",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
  },
  subText: {
    fontSize: 13,
    color: "#6c626b",
    fontFamily: "Rubik, sans-serif",
    fontWeight: 700,
    backgroundColor: "#fff",
    border: "1px solid #f0e6ee",
    borderRadius: 999,
    padding: "3px 9px",
  },
  statusChip: {
    height: 24,
    backgroundColor: "#edf8f0",
    color: "#2e7d32",
    border: "1px solid #d7eedb",
    fontFamily: "Rubik, sans-serif",
    fontWeight: "800 !important" as const,
    fontSize: "0.74rem !important",
  },
  archivedStatusChip: {
    backgroundColor: "#fff1f1 !important",
    color: "#b42318 !important",
    border: "1px solid #ffd6d2 !important",
  },
  content: {
    padding: "16px",
    backgroundColor: "#faf8fa",
    maxHeight: "calc(100vh - 340px)",
    overflowY: "auto",
    scrollbarWidth: "thin" as const,
    "& .MuiDivider-root": {
      margin: "6px 0",
      borderColor: "#f1e9ef",
    },
  },
  section: {
    backgroundColor: "#fff",
    border: "1px solid #f0ecef",
    borderRadius: 16,
    padding: "14px 14px 12px",
    marginBottom: 14,
    boxShadow: "0 4px 16px rgba(45, 35, 43, 0.045)",
  },
  sectionTitle: {
    fontFamily: "Rubik, sans-serif",
    fontWeight: "900 !important" as const,
    color: "#7a3e6b",
    fontSize: "0.92rem !important",
    marginBottom: "8px !important",
  },
  rowIcon: {
    color: "#7a3e6b",
    fontSize: "1.12rem !important",
  },
  actionsRow: {
    marginTop: 6,
    marginBottom: 12,
  },
  dangerSection: {
    marginTop: 14,
    padding: "14px",
    backgroundColor: "#fff",
    border: "1px solid #f3c8c4",
    borderRadius: 16,
    boxShadow: "0 4px 16px rgba(180, 35, 24, 0.05)",
  },
  dangerSectionTitle: {
    fontFamily: "Rubik, sans-serif",
    fontWeight: "900 !important" as const,
    color: "#b42318",
    fontSize: "0.92rem !important",
    marginBottom: "10px !important",
  },
  dangerButton: {
    minHeight: 42,
    borderRadius: "12px !important",
    fontFamily: "Rubik, sans-serif !important",
    fontWeight: "800 !important" as const,
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  deleteIconButton: {
    width: 40,
    height: 40,
    color: "#b42318 !important",
    backgroundColor: "#fff5f5 !important",
    border: "1px solid #ffd6d2 !important",
    "&:hover": {
      color: "#fff !important",
      backgroundColor: "#b42318 !important",
      borderColor: "#b42318 !important",
    },
    "&.Mui-disabled": {
      color: "#d9a6a0 !important",
      backgroundColor: "#fff8f8 !important",
      borderColor: "#f3d6d3 !important",
    },
  },
  restoreButton: {
    minHeight: 42,
    borderRadius: "12px !important",
    borderColor: "#d9bfd2 !important",
    color: "#7a3e6b !important",
    backgroundColor: "#fff",
    fontFamily: "Rubik, sans-serif !important",
    fontWeight: "800 !important" as const,
    "&:hover": {
      backgroundColor: "#f8f1f6",
      borderColor: "#9a5188 !important",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  buttonContained: {
    minHeight: 42,
    borderRadius: "12px !important",
    background: "linear-gradient(135deg, #9a5188 0%, #7a3e6b 100%)",
    color: "#fff",
    fontWeight: "700 !important" as const,
    fontFamily: "Rubik, sans-serif",
    boxShadow: "0 6px 16px rgba(122, 62, 107, 0.18)",
    "&:hover": {
      background: "linear-gradient(135deg, #7a3e6b 0%, #9a5188 100%)",
      boxShadow: "0 8px 20px rgba(122, 62, 107, 0.24)",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  buttonOutlined: {
    minHeight: 42,
    borderRadius: "12px !important",
    borderColor: "#d9bfd2 !important",
    color: "#7a3e6b !important",
    backgroundColor: "#fff",
    fontWeight: "700 !important" as const,
    fontFamily: "Rubik, sans-serif",
    "&:hover": {
      backgroundColor: "#f8f1f6",
      borderColor: "#9a5188 !important",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  closeButton: {
    marginTop: 10,
    minHeight: 42,
    borderRadius: "12px !important",
    backgroundColor: "#fff",
    border: "1px solid #ead8e5",
    fontFamily: "Rubik, sans-serif",
    fontWeight: "800 !important" as const,
    color: "#5f5660",
    "&:hover": {
      backgroundColor: "#f7f1f5",
      borderColor: "#d9bfd2",
    },
  },
  eventListItem: {
    padding: "14px",
    borderRadius: 14,
    backgroundColor: "#fff",
    border: "1px solid #f0e6ee",
    boxShadow: "0 4px 14px rgba(45, 35, 43, 0.045)",
  },
  eventListTitle: {
    fontFamily: "Rubik, sans-serif !important",
    fontWeight: "900 !important" as const,
    color: "#2f2930",
    lineHeight: "1.35 !important" as const,
  },
  eventListMeta: {
    marginTop: "5px !important",
    fontFamily: "Rubik, sans-serif !important",
    fontSize: "0.86rem !important",
    color: "#665e66",
    fontWeight: "700 !important" as const,
  },
  eventListSecondary: {
    marginTop: "8px !important",
    fontFamily: "Rubik, sans-serif !important",
    fontSize: "0.78rem !important",
    color: "#8a7f89",
    fontWeight: "700 !important" as const,
  },
  eventStatusChip: {
    height: 24,
    flexShrink: 0,
    backgroundColor: "#edf8f0 !important",
    color: "#2e7d32 !important",
    border: "1px solid #d7eedb !important",
    fontFamily: "Rubik, sans-serif !important",
    fontWeight: "800 !important" as const,
  },
  pastEventStatusChip: {
    backgroundColor: "#f2f3f5 !important",
    color: "#5f6670 !important",
    border: "1px solid #e1e4e8 !important",
  },
  "@media (max-width: 900px)": {
    panel: {
      flex: "0 0 auto",
      width: "100%",
      maxHeight: "none",
    },
  },
});
