import { makeStyles } from "@mui/styles";

export const useVolunteerDetailsStyles = makeStyles({
  "@global": {
    ":root": {
      "--people-surface": "#ffffff",
      "--people-surface-raised": "rgba(255, 255, 255, 0.86)",
      "--people-surface-soft": "#f7f8fa",
      "--people-surface-tint": "#f7f2f6",
      "--people-border": "#e6e1e6",
      "--people-border-strong": "#d6c8d3",
      "--people-text": "#1f1f23",
      "--people-text-muted": "#6d6670",
      "--people-primary": "var(--color-primary)",
      "--people-primary-strong": "var(--color-primary-dark)",
      "--people-primary-soft": "var(--color-primary-soft)",
      "--people-success": "var(--color-success)",
      "--people-success-soft": "var(--color-success-soft)",
      "--people-danger": "#b42318",
      "--people-danger-soft": "#fff1ef",
      "--people-focus": "rgba(var(--color-primary-rgb), 0.34)",
      "--people-shadow-soft": "0 16px 44px rgba(31, 31, 35, 0.11)",
      "--people-shadow-card": "0 8px 24px rgba(31, 31, 35, 0.07)",
    },
  },
  panel: {
    flex: "0 0 clamp(340px, 31vw, 440px)",
    minWidth: 0,
    maxHeight: "calc(100dvh - 220px)",
    borderRadius: 22,
    overflow: "hidden",
    boxShadow: "var(--people-shadow-soft)",
    fontFamily: "inherit",
    direction: "rtl",
    backgroundColor: "var(--people-surface-raised)",
    backdropFilter: "blur(22px) saturate(170%)",
    border: "1px solid rgba(255, 255, 255, 0.68)",
    animation: "peopleSheetIn 260ms cubic-bezier(0.2, 0.8, 0.2, 1)",
    "@media (prefers-reduced-motion: reduce)": {
      animation: "none",
    },
    "@media (prefers-reduced-transparency: reduce), (prefers-contrast: more)": {
      backgroundColor: "var(--people-surface)",
      backdropFilter: "none",
      border: "1px solid var(--people-border-strong)",
    },
  },
  header: {
    padding: "18px 18px 16px",
    background:
      "linear-gradient(180deg, rgba(255,255,255,0.92) 0%, rgba(247,248,250,0.78) 100%)",
    color: "var(--people-text)",
    borderBottom: "1px solid var(--people-border)",
  },
  closeIconButton: {
    color: "var(--people-primary)",
    backgroundColor: "rgba(255,255,255,0.82)",
    border: "1px solid var(--people-border)",
    width: 44,
    height: 44,
    flexShrink: 0,
    transition: "background-color 140ms ease, color 140ms ease, transform 140ms ease",
    "&:hover": {
      backgroundColor: "var(--people-primary)",
      color: "#fff",
      borderColor: "var(--people-primary)",
    },
    "&:active": {
      transform: "scale(0.96)",
    },
    "&.Mui-focusVisible": {
      boxShadow: "0 0 0 4px var(--people-focus)",
    },
    "@media (prefers-reduced-motion: reduce)": {
      transition: "none",
      "&:active": {
        transform: "none",
      },
    },
  },
  avatar: {
    width: 60,
    height: 60,
    backgroundColor: "var(--people-primary-soft)",
    color: "var(--people-primary)",
    fontWeight: 900,
    fontSize: 18,
    fontFamily: "inherit",
    border: "1px solid var(--people-border)",
    boxShadow: "0 8px 22px rgba(var(--color-primary-rgb), 0.12)",
  },
  nameText: {
    fontWeight: "900 !important" as const,
    fontFamily: "inherit",
    color: "var(--people-text)",
    lineHeight: "1.25 !important" as const,
    maxWidth: "100%",
  },
  entityChip: {
    height: 24,
    width: "fit-content",
    marginTop: "6px !important",
    backgroundColor: "var(--people-primary-soft)",
    color: "var(--people-primary)",
    border: "1px solid var(--people-border)",
    fontFamily: "inherit",
    fontWeight: "800 !important" as const,
    fontSize: "0.74rem !important",
  },
  headerMeta: {
    marginTop: "8px !important",
    flexWrap: "wrap" as const,
    rowGap: 6,
  },
  nationalIdActions: {
    flexShrink: 0,
    padding: "2px",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.9)",
    border: "1px solid var(--people-border)",
  },
  nationalIdActionButton: {
    minWidth: 44,
    minHeight: 36,
    padding: "4px 9px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    fontFamily: "inherit",
    color: "var(--people-primary)",
    "&:hover": {
      backgroundColor: "var(--people-primary-soft)",
    },
    "&.Mui-focusVisible": {
      boxShadow: "0 0 0 4px var(--people-focus)",
    },
  },
  nationalIdStatus: {
    display: "block",
    marginTop: 6,
    color: "var(--people-primary)",
    fontFamily: "inherit",
    fontWeight: 700,
  },
  subText: {
    fontSize: 13,
    color: "var(--people-text-muted)",
    fontFamily: "inherit",
    fontWeight: 700,
    backgroundColor: "rgba(255,255,255,0.9)",
    border: "1px solid var(--people-border)",
    borderRadius: 999,
    padding: "3px 9px",
  },
  statusChip: {
    height: 24,
    backgroundColor: "var(--people-success-soft)",
    color: "var(--people-success)",
    border: "1px solid var(--color-success-border)",
    fontFamily: "inherit",
    fontWeight: "800 !important" as const,
    fontSize: "0.74rem !important",
  },
  archivedStatusChip: {
    backgroundColor: "var(--people-danger-soft) !important",
    color: "var(--people-danger) !important",
    border: "1px solid #ffd6d2 !important",
  },
  content: {
    padding: "16px",
    backgroundColor: "var(--people-surface-soft)",
    maxHeight: "calc(100dvh - 328px)",
    overflowY: "auto",
    scrollbarWidth: "thin" as const,
    "& .MuiDivider-root": {
      margin: "6px 0",
      borderColor: "var(--people-border)",
    },
    "@media (max-width: 900px)": {
      maxHeight: "calc(78dvh - 138px)",
    },
  },
  section: {
    backgroundColor: "var(--people-surface)",
    border: "1px solid var(--people-border)",
    borderRadius: 16,
    padding: "14px 14px 12px",
    marginBottom: 14,
    boxShadow: "var(--people-shadow-card)",
  },
  sectionTitle: {
    fontFamily: "inherit",
    fontWeight: "900 !important" as const,
    color: "var(--people-primary)",
    fontSize: "0.92rem !important",
    marginBottom: "8px !important",
  },
  rowIcon: {
    color: "var(--people-primary)",
    fontSize: "1.12rem !important",
  },
  actionsRow: {
    marginTop: 6,
    marginBottom: 12,
  },
  dangerSection: {
    marginTop: 14,
    padding: "14px",
    backgroundColor: "var(--people-surface)",
    border: "1px solid #f1b8b2",
    borderRadius: 16,
    boxShadow: "0 4px 16px rgba(180, 35, 24, 0.05)",
  },
  dangerSectionTitle: {
    fontFamily: "inherit",
    fontWeight: "900 !important" as const,
    color: "var(--people-danger)",
    fontSize: "0.92rem !important",
    marginBottom: "10px !important",
  },
  dangerButton: {
    minHeight: 44,
    borderRadius: "12px !important",
    fontFamily: "inherit !important",
    fontWeight: "800 !important" as const,
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  deleteIconButton: {
    width: 44,
    height: 44,
    color: "var(--people-danger) !important",
    backgroundColor: "var(--people-danger-soft) !important",
    border: "1px solid #ffd6d2 !important",
    "&:hover": {
      color: "#fff !important",
      backgroundColor: "var(--people-danger) !important",
      borderColor: "var(--people-danger) !important",
    },
    "&.Mui-focusVisible": {
      boxShadow: "0 0 0 4px rgba(180, 35, 24, 0.22)",
    },
    "&.Mui-disabled": {
      color: "#d9a6a0 !important",
      backgroundColor: "#fff8f8 !important",
      borderColor: "#f3d6d3 !important",
    },
  },
  restoreButton: {
    minHeight: 44,
    borderRadius: "12px !important",
    borderColor: "#d9bfd2 !important",
    color: "var(--people-primary) !important",
    backgroundColor: "#fff",
    fontFamily: "inherit !important",
    fontWeight: "800 !important" as const,
    "&:hover": {
      backgroundColor: "var(--people-surface-tint)",
      borderColor: "var(--people-primary) !important",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  buttonContained: {
    minHeight: 44,
    borderRadius: "12px !important",
    background: "linear-gradient(135deg, var(--color-primary) 0%, var(--people-primary) 100%)",
    color: "#fff",
    fontWeight: "700 !important" as const,
    fontFamily: "inherit",
    boxShadow: "0 6px 16px rgba(var(--color-primary-rgb), 0.18)",
    "&:hover": {
      background: "linear-gradient(135deg, var(--people-primary-strong) 0%, var(--people-primary) 100%)",
      boxShadow: "0 8px 20px rgba(var(--color-primary-rgb), 0.24)",
    },
    "&:active": {
      transform: "scale(0.985)",
    },
    "&.Mui-focusVisible": {
      boxShadow: "0 0 0 4px var(--people-focus)",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  buttonOutlined: {
    minHeight: 44,
    borderRadius: "12px !important",
    borderColor: "var(--people-border-strong) !important",
    color: "var(--people-primary) !important",
    backgroundColor: "var(--people-surface)",
    fontWeight: "700 !important" as const,
    fontFamily: "inherit",
    "&:hover": {
      backgroundColor: "var(--people-surface-tint)",
      borderColor: "var(--people-primary) !important",
    },
    "&:active": {
      transform: "scale(0.985)",
    },
    "&.Mui-focusVisible": {
      boxShadow: "0 0 0 4px var(--people-focus)",
    },
    "& .MuiButton-startIcon": {
      marginLeft: 6,
      marginRight: 0,
    },
  },
  closeButton: {
    marginTop: 10,
    minHeight: 44,
    borderRadius: "12px !important",
    backgroundColor: "var(--people-surface)",
    border: "1px solid var(--people-border)",
    fontFamily: "inherit",
    fontWeight: "800 !important" as const,
    color: "var(--people-text-muted)",
    "&:hover": {
      backgroundColor: "var(--people-surface-tint)",
      borderColor: "var(--people-border-strong)",
    },
  },
  eventListItem: {
    padding: "14px",
    borderRadius: 14,
    backgroundColor: "var(--people-surface)",
    border: "1px solid var(--people-border)",
    boxShadow: "0 4px 14px rgba(45, 35, 43, 0.045)",
  },
  eventListTitle: {
    fontFamily: "inherit !important",
    fontWeight: "900 !important" as const,
    color: "var(--people-text)",
    lineHeight: "1.35 !important" as const,
  },
  eventListMeta: {
    marginTop: "5px !important",
    fontFamily: "inherit !important",
    fontSize: "0.86rem !important",
    color: "var(--people-text-muted)",
    fontWeight: "700 !important" as const,
  },
  eventListSecondary: {
    marginTop: "8px !important",
    fontFamily: "inherit !important",
    fontSize: "0.78rem !important",
    color: "var(--people-text-muted)",
    fontWeight: "700 !important" as const,
  },
  eventStatusChip: {
    height: 24,
    flexShrink: 0,
    backgroundColor: "var(--color-success-soft) !important",
    color: "var(--color-success) !important",
    border: "1px solid var(--color-success-border) !important",
    fontFamily: "inherit !important",
    fontWeight: "800 !important" as const,
  },
  pastEventStatusChip: {
    backgroundColor: "#f2f3f5 !important",
    color: "#5f6670 !important",
    border: "1px solid #e1e4e8 !important",
  },
  "@media (max-width: 900px)": {
    panel: {
      flex: "0 0 auto",
      width: "100%",
      maxHeight: "min(78dvh, 680px)",
    },
  },
  "@keyframes peopleSheetIn": {
    "0%": {
      opacity: 0,
      transform: "translateY(10px) scale(0.985)",
    },
    "100%": {
      opacity: 1,
      transform: "translateY(0) scale(1)",
    },
  },
  "@media (prefers-reduced-motion: reduce)": {
    buttonContained: {
      transition: "none !important",
      "&:active": {
        transform: "none",
      },
    },
    buttonOutlined: {
      transition: "none !important",
      "&:active": {
        transform: "none",
      },
    },
  },
});
